# Generated by Django 4.0.4 on 2022-04-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_student_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('SQP', 'StemQuest Program'), ('OCC', 'On Choice Camps'), ('HC', 'Holidays Camps')], default='SQP', max_length=5)),
            ],
        ),
    ]
