# Generated by Django 4.0.4 on 2022-04-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_membership_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'CASH'), ('CHEQUE', 'CHEQUE'), ('CREDIT CARD', 'Bank Credit Card')], default='CASH', max_length=50),
        ),
    ]
