# Generated by Django 4.0.4 on 2022-05-01 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_membership_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='Casablanca', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='birthday',
            field=models.CharField(default='01/01/2022', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='maker@makerlab.ma', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('TM', 'Tiny Makers'), ('MM', 'Tiny Makers'), ('MC', 'Tiny Makers')], default='MM', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=models.CharField(default='0621877106', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='medias/profile_pic'),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
