# Generated by Django 4.0.4 on 2022-05-14 08:51

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_gender', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother')], default='Father', max_length=10)),
                ('fullname', models.CharField(max_length=30)),
                ('phone', phone_field.models.PhoneField(max_length=31)),
                ('address', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('StemQuest', 'StemQuest'), ('On choice Camps', 'On choice Camps'), ('Experience-It', 'Experience-It'), ('Holidays camps', 'Holidays camps')], default='StemQuest', max_length=50)),
                ('price', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('start_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Boy', 'Boy'), ('Girl', 'Girl')], default='Boy', max_length=10)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('level', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Annuel', 'Annuel'), ('Trimestriel', 'Trimestriel'), ('Mensuel', 'Mensuel')], default='Trimestriel', max_length=15)),
                ('price', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscriptions.contacts')),
                ('student', models.ManyToManyField(to='inscriptions.students')),
            ],
        ),
        migrations.CreateModel(
            name='Inscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscriptions.contacts')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscriptions.programs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscriptions.students')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscriptions.subscriptions')),
            ],
        ),
    ]
